all : cleanup restore build test
runapp: restore build run
 
cleanup:
	dotnet clean
 
restore:
	dotnet restore
 
build:
	dotnet build

test:
	dotnet test ./NancyApplication.Tests/
 
run:
	dotnet run --project ./NancyApplication/NancyApplication.csproj